# Project information
site_name: Python Registerer
site_url: https://danialkeimasi.github.io/python-registerer
site_author: Danial Keimasi
site_description: >-
  Implement maintainable and easy to use registry patterns in your project.

# Repository
repo_name: danialkeimasi/python-registerer
repo_url: https://github.com/danialkeimasi/python-registerer

nav:
  - Overview: index.md
  - Usage: usage.md
  - References:
      - Registerer: references/registerer.md
      - Validators: references/validators.md
      - Exceptions: references/exceptions.md

theme:
  name: "material"
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite

  - pymdownx.superfences:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true

  - markdown-exec
  - social:
      icon: fontawesome/brands/github-alt

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danialkeimasi/python-registerer
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/registerer/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/danialkeimasi
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/danialkeimasi
